#pragma once

#include <QColor>
#include <QMap>
#include <QStringList>
#include <QStyle>

#include "QtnRibbonMainWindow.h"
#include "QtnRibbonStyle.h"

#include "crs/CrsTypes.h"
#include "domain/AnalysisData.h"
#include "domain/RuleBasedClearanceEngine.h"
#include "route/InspectionRoutePlanning.h"
#include "route/PowerlineRouteTypes.h"

class QAction;
class QActionGroup;
class QByteArray;
class QCheckBox;
class QComboBox;
class QCloseEvent;
class QDialog;
class QDockWidget;
class QDoubleSpinBox;
class QDragEnterEvent;
class QDropEvent;
class QEvent;
class QFormLayout;
class QGroupBox;
class QIcon;
class QLabel;
class QLineEdit;
class QListWidget;
class QListWidgetItem;
class QObject;
class QPlainTextEdit;
class QProgressBar;
class QPushButton;
class QSlider;
class QSpinBox;
class QMenu;
class QTabWidget;
class QTableWidget;
class QTableWidgetItem;
class QTextEdit;
class QTreeWidget;
class QTreeWidgetItem;
class QToolButton;
class QToolBar;
class QTranslator;
class QWidget;

namespace Qtitan
{
class RibbonBar;
class RibbonBackstageView;
class RibbonGroup;
class RibbonPage;
class RibbonSystemButton;
}

class PointCloudViewer;
class ProfilePlotWidget;
struct ClearanceAnalysisResult;

class MainWindow final : public Qtitan::RibbonMainWindow
{
    Q_OBJECT

public:
    enum class UiLanguage
    {
        English,
        Chinese
    };

    explicit MainWindow(QTranslator* appTranslator, QTranslator* qtTranslator, QWidget* parent = nullptr);
    ~MainWindow() override = default;

protected:
    void closeEvent(QCloseEvent* event) override;
    void dragEnterEvent(QDragEnterEvent* event) override;
    void dropEvent(QDropEvent* event) override;
    bool eventFilter(QObject* watched, QEvent* event) override;
    void changeEvent(QEvent* event) override;
#ifdef Q_OS_WIN
    bool nativeEvent(const QByteArray& eventType, void* message, long* result) override;
#endif

private:
    enum class LogLevel
    {
        Info,
        Warning,
        Error
    };

    void createActions();
    void createRibbon();
    void createBackstageView();
    void createViewQuickToolBar();
    void createWindowControls();
    void createProjectDock();
    void createInspectorPanel();
    void createRouteDetailsDock();
    void createProfileClassificationDock();
    void createProfileDock();
    void createLogDock();
    void createStatusBar();
    void createConnections();
    void retranslateUi();
    void openBackstagePage(QWidget* page);
    void hideBackstageView();
    void refreshBackstageRecentProjects();
    void refreshBackstageProjectPropertiesPage();
    void refreshBackstageApplicationSettingsPage();
    void refreshBackstageAboutPage();
    void openProjectFromBackstage();
    void openProjectExplorerFile();
    void openPointCloud();
    void addPointCloudFiles();
    void openProject();
    void saveProject();
    void saveProjectAs();
    void openProjectCoordinateSystems();
    bool loadPointCloudFile(const QString& filePath);
    bool loadPointCloudFiles(const QStringList& filePaths);
    bool appendPointCloudFiles(const QStringList& filePaths);
    bool loadProjectFile(const QString& filePath);
    bool saveProjectFile(const QString& filePath);
    void clearPointCloud();
    void removeSelectedDataset();
    void choosePointColor();
    void chooseBackgroundColor();
    void chooseRouteWaypointColor();
    void chooseRoutePartPointColor();
    void chooseRouteTrajectoryColor();
    void applyOfficeTheme(Qtitan::RibbonStyle::Theme theme);
    void updateWindowChromePalette(Qtitan::RibbonStyle::Theme theme);
    void updateWindowControlButtons();
    void updateWindowControlAppearance(Qtitan::RibbonStyle::Theme theme);
    void toggleMaximizedWindow();
    bool isDraggableRibbonArea(const QPoint& position) const;
    bool isInteractiveRibbonWidget(const QWidget* widget) const;
    bool isWindowControlWidget(const QWidget* widget) const;
    void syncUiFromViewer();
    void updateDatasetPanel();
    void updateActionState();
    void setColorButtonAppearance(QPushButton* button, const QColor& color, const QString& fallbackText) const;
    void appendLog(LogLevel level, const QString& message);
    void showUserMessage(LogLevel level, const QString& message, int timeoutMs = 3000);
    void refreshLogPanel();
    void exportLogEntries();
    void loadVisualizationSettings();
    void persistVisualizationSettings() const;
    void loadInteractionSettings();
    void persistInteractionSettings() const;
    void loadMeasurementSettings();
    void persistMeasurementSettings() const;
    void loadLanguageSettings();
    void persistLanguageSettings() const;
    void loadWindowSettings();
    void persistWindowSettings() const;
    void loadThemeSettings();
    void persistThemeSettings() const;
    void syncProfileDockForMeasurementMode(bool measurementEnabled);
    void beginOperationProgress(const QString& message);
    void updateOperationProgress(const QString& message, int value, int maximum);
    void endOperationProgress();
    void updateNavigationHelpText();
    void updateMeasurementPanel();
    void updateClearanceSegmentsTable(const ClearanceAnalysisResult& clearanceAnalysis);
    void updateVegetationRiskPanel();
    void updateRoutePlanningPanel();
    void ensureRouteRoamFloatingDialog();
    void syncRouteRoamFloatingDialog();
    void handleRouteRoamPhotoCaptured(int waypointIndex, int targetIndex, const QString& targetLabel, int captureCount);
    void applyRouteWaypointTableColumnVisibility();
    void applyRoutePartTableColumnVisibility();
    void focusRoutePartPoint(int partIndex);
    void focusRouteWaypoint(int waypointIndex);
    void focusRouteQaIssue(int issueIndex);
    bool ensureRouteEditingEnabled(bool notify = true);
    void setRouteEditingEnabled(bool enabled, bool notify = true);
    bool editRouteWaypoint(int waypointIndex);
    bool removeRoutePartPoint(int partIndex, bool notify = true);
    bool removeRouteWaypoint(int waypointIndex, bool notify = true);
    void rebuildProjectTree();
    void refreshProjectTreeFilter();
    void focusProjectTreeItem(QTreeWidgetItem* item);
    void applyProjectTreeItemCheckState(QTreeWidgetItem* item);
    void showProjectTreeContextMenu(const QPoint& pos);
    void setProjectTreeGroupVisibility(const QString& groupType, bool visible);
    void clearAllProjectImages();
    bool attachImageToIssue(int issueIndex);
    void showPointCloudDatasetDetails(const QString& filePath);
    void showInspectionRouteDetails() const;
    void syncDataManagerTrajectory() const;
    void updateTowerPanel();
    void updateIssuePanel();
    void updateTowerDetailEditor();
    void updateIssueDetailEditor();
    QWidget* createSliderControl(QSlider*& slider, QLabel*& valueLabel, int minimum, int maximum, int step);
    void updateSliderValueLabel(QSlider* slider, QLabel* valueLabel, const QString& formatText) const;
    void updateVisualizationTooltips();
    void adjustClassificationColorTableHeight();
    void updateClassificationColorTable();
    void updateProfileClassificationPanel();
    bool saveProfileClassificationEditsToLas();
    void promptSaveProfileClassificationEditsIfNeeded();
    bool importTowerFile(const QString& filePath, bool updateLink = true, bool notify = true);
    bool exportTowerFile(const QString& filePath, bool updateLink = true, bool notify = true);
    bool reloadLinkedTowerFile(bool notify = true);
    bool importRouteFile(const QString& filePath, bool updateLink = true, bool notify = true);
    bool exportRouteFile(const QString& filePath, bool updateLink = true, bool notify = true);
    bool reloadLinkedRouteFile(bool notify = true);
    void applyCurrentRouteToViewer();
    void showRouteDetailsDock(int preferredTab = 0);
    QString nextDefaultTowerName() const;
    QString nextDefaultIssueTitle() const;
    QString selectedDatasetPath() const;
    void setTowerEditingEnabled(bool enabled);
    void syncProjectCoordinateSystemsFromRoutePlanning();
    void syncRoutePlanningFromProjectCoordinateSystems();
    void applyLanguage(UiLanguage language);

    PointCloudViewer* viewer_ = nullptr;
    Qtitan::RibbonBar* ribbonBar_ = nullptr;
    Qtitan::RibbonSystemButton* backstageSystemButton_ = nullptr;
    Qtitan::RibbonBackstageView* backstageView_ = nullptr;
    QDockWidget* projectDock_ = nullptr;
    QDockWidget* inspectorDock_ = nullptr;
    QDockWidget* routeDetailsDock_ = nullptr;
    QDockWidget* profileClassificationDock_ = nullptr;
    QDockWidget* profileDock_ = nullptr;
    QDockWidget* logDock_ = nullptr;
    QTabWidget* inspectorTabWidget_ = nullptr;
    QTabWidget* routeDetailsTabWidget_ = nullptr;
    QTranslator* appTranslator_ = nullptr;
    QTranslator* qtTranslator_ = nullptr;
    UiLanguage currentLanguage_ = UiLanguage::English;

    Qtitan::RibbonPage* homePage_ = nullptr;
    Qtitan::RibbonPage* routePage_ = nullptr;
    Qtitan::RibbonPage* analysisPage_ = nullptr;
    Qtitan::RibbonPage* issuePage_ = nullptr;
    Qtitan::RibbonPage* towerPage_ = nullptr;
    Qtitan::RibbonPage* appearancePage_ = nullptr;
    QAction* backstageOpenPageAction_ = nullptr;
    QAction* backstageOpenProjectPageAction_ = nullptr;
    QAction* backstageSaveAction_ = nullptr;
    QAction* backstageSaveAsAction_ = nullptr;
    QAction* backstageProjectPropertiesPageAction_ = nullptr;
    QAction* backstageApplicationSettingsPageAction_ = nullptr;
    QAction* backstageAboutPageAction_ = nullptr;
    QAction* backstageExitAction_ = nullptr;
    Qtitan::RibbonGroup* datasetRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* cameraRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* sceneRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* measureRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* classificationRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* vegetationRiskRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* routePlanningRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* routeFileRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* issueRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* workspaceRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* towerRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* colorRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* themeRibbonGroup_ = nullptr;
    Qtitan::RibbonGroup* languageRibbonGroup_ = nullptr;
    QWidget* backstageOpenPage_ = nullptr;
    QWidget* backstageOpenProjectPage_ = nullptr;
    QWidget* backstageProjectPropertiesPage_ = nullptr;
    QWidget* backstageApplicationSettingsPage_ = nullptr;
    QWidget* backstageAboutPage_ = nullptr;

    QGroupBox* datasetGroupBox_ = nullptr;
    QFormLayout* datasetLayout_ = nullptr;
    QGroupBox* renderingGroupBox_ = nullptr;
    QGroupBox* classificationColorsGroupBox_ = nullptr;
    QGroupBox* profileClassificationGroupBox_ = nullptr;
    QFormLayout* renderingLayout_ = nullptr;
    QGroupBox* measurementGroupBox_ = nullptr;
    QFormLayout* measurementLayout_ = nullptr;
    QGroupBox* clearanceGroupBox_ = nullptr;
    QFormLayout* clearanceLayout_ = nullptr;
    QGroupBox* clearanceSegmentsGroupBox_ = nullptr;
    QGroupBox* analysisParametersGroupBox_ = nullptr;
    QFormLayout* analysisParametersLayout_ = nullptr;
    QGroupBox* vegetationRisksGroupBox_ = nullptr;
    QGroupBox* routePlanningGroupBox_ = nullptr;
    QGroupBox* routePartsGroupBox_ = nullptr;
    QGroupBox* routeWaypointsGroupBox_ = nullptr;
    QGroupBox* routeWaypointTargetsGroupBox_ = nullptr;
    QGroupBox* routeQaGroupBox_ = nullptr;
    QGroupBox* navigationGroupBox_ = nullptr;
    QFormLayout* navigationToggleLayout_ = nullptr;
    QGroupBox* towerDetailsGroupBox_ = nullptr;
    QFormLayout* towerDetailsLayout_ = nullptr;
    QGroupBox* issueDetailsGroupBox_ = nullptr;
    QFormLayout* issueDetailsLayout_ = nullptr;

    QLabel* datasetNameValueLabel_ = nullptr;
    QLabel* datasetPathValueLabel_ = nullptr;
    QLabel* datasetPointsValueLabel_ = nullptr;
    QLabel* datasetBoundsValueLabel_ = nullptr;
    QLabel* datasetExtentValueLabel_ = nullptr;
    QLabel* datasetColorValueLabel_ = nullptr;
    QLabel* measurementStartValueLabel_ = nullptr;
    QLabel* measurementEndValueLabel_ = nullptr;
    QLabel* measurementDistanceValueLabel_ = nullptr;
    QLabel* measurementHorizontalDistanceValueLabel_ = nullptr;
    QLabel* measurementDeltaZValueLabel_ = nullptr;
    QLabel* measurementSegmentsValueLabel_ = nullptr;
    QLabel* clearanceShortestValueLabel_ = nullptr;
    QLabel* clearanceWarningCountValueLabel_ = nullptr;
    QLabel* clearanceStatusValueLabel_ = nullptr;
    QLabel* clearanceSegmentsSummaryLabel_ = nullptr;
    QLabel* clearanceRuleBandsValueLabel_ = nullptr;
    QLabel* vegetationRiskCountValueLabel_ = nullptr;
    QLabel* vegetationRiskStatusValueLabel_ = nullptr;
    QLabel* vegetationRiskSummaryLabel_ = nullptr;
    QLabel* routeStatusValueLabel_ = nullptr;
    QLabel* routeSummaryValueLabel_ = nullptr;
    QLabel* routeQaSummaryValueLabel_ = nullptr;
    QLabel* towerCountValueLabel_ = nullptr;
    QLabel* towerToolStatusLabel_ = nullptr;
    QLabel* issueCountValueLabel_ = nullptr;
    QLabel* issueToolStatusLabel_ = nullptr;
    QLabel* issueLocationValueLabel_ = nullptr;
    QLabel* issueCreatedAtValueLabel_ = nullptr;
    QLabel* backstageOpenTitleLabel_ = nullptr;
    QLabel* backstageOpenSubtitleLabel_ = nullptr;
    QLabel* backstageOpenProjectTitleLabel_ = nullptr;
    QLabel* backstageOpenProjectSubtitleLabel_ = nullptr;
    QLabel* backstageProjectPropertiesTitleLabel_ = nullptr;
    QLabel* backstageProjectPropertiesSubtitleLabel_ = nullptr;
    QLabel* backstageProjectFileValueLabel_ = nullptr;
    QLabel* backstageProjectDatasetCountValueLabel_ = nullptr;
    QLabel* backstageProjectCoordinateSystemsValueLabel_ = nullptr;
    QLabel* backstageApplicationSettingsTitleLabel_ = nullptr;
    QLabel* backstageApplicationSettingsSubtitleLabel_ = nullptr;
    QLabel* backstageAboutTitleLabel_ = nullptr;
    QLabel* backstageAboutSubtitleLabel_ = nullptr;
    QLabel* backstageAboutBodyLabel_ = nullptr;

    QWidget* pointSizeControl_ = nullptr;
    QWidget* pointOpacityControl_ = nullptr;
    QWidget* depthCueControl_ = nullptr;
    QWidget* edlStrengthControl_ = nullptr;
    QWidget* wheelZoomSensitivityControl_ = nullptr;
    QSlider* pointSizeSlider_ = nullptr;
    QSlider* pointOpacitySlider_ = nullptr;
    QSlider* depthCueSlider_ = nullptr;
    QSlider* edlStrengthSlider_ = nullptr;
    QSlider* wheelZoomSensitivitySlider_ = nullptr;
    QLabel* pointSizeValueLabel_ = nullptr;
    QLabel* pointOpacityValueLabel_ = nullptr;
    QLabel* depthCueValueLabel_ = nullptr;
    QLabel* edlStrengthValueLabel_ = nullptr;
    QLabel* wheelZoomSensitivityValueLabel_ = nullptr;
    QComboBox* colorModeComboBox_ = nullptr;
    QPushButton* pointColorButton_ = nullptr;
    QPushButton* backgroundColorButton_ = nullptr;
    QPushButton* measurementToggleButton_ = nullptr;
    QPushButton* measurementClearButton_ = nullptr;
    QDoubleSpinBox* clearanceThresholdSpinBox_ = nullptr;
    QComboBox* clearanceRulePresetComboBox_ = nullptr;
    QDoubleSpinBox* vegetationSearchRadiusSpinBox_ = nullptr;
    QDoubleSpinBox* vegetationClusterGapSpinBox_ = nullptr;
    QSpinBox* vegetationClusterPointCountSpinBox_ = nullptr;
    QComboBox* aircraftProfileComboBox_ = nullptr;
    QDoubleSpinBox* routeSafetyHeightSpinBox_ = nullptr;
    QDoubleSpinBox* routeWaypointSpeedSpinBox_ = nullptr;
    QDoubleSpinBox* routeWaypointSpacingSpinBox_ = nullptr;
    QDoubleSpinBox* routeSmoothingStrengthSpinBox_ = nullptr;
    QDoubleSpinBox* routeHeightOffsetSpinBox_ = nullptr;
    QDoubleSpinBox* routeRoamSpeedSpinBox_ = nullptr;
    QComboBox* routeRoamViewModeComboBox_ = nullptr;
    QWidget* routeRoamControlsRow_ = nullptr;
    QPushButton* routeRoamStartButton_ = nullptr;
    QPushButton* routeRoamPauseResumeButton_ = nullptr;
    QPushButton* routeRoamStopButton_ = nullptr;
    QDialog* routeRoamFloatingDialog_ = nullptr;
    QDoubleSpinBox* routeRoamFloatingSpeedSpinBox_ = nullptr;
    QComboBox* routeRoamFloatingViewModeComboBox_ = nullptr;
    QLabel* routeRoamFloatingCaptureLabel_ = nullptr;
    QComboBox* profileClassificationModeComboBox_ = nullptr;
    QComboBox* routeWaypointLabelModeComboBox_ = nullptr;
    QComboBox* routePartLabelModeComboBox_ = nullptr;
    QPushButton* routeWaypointColorButton_ = nullptr;
    QPushButton* routePartPointColorButton_ = nullptr;
    QPushButton* routeTrajectoryColorButton_ = nullptr;
    QCheckBox* roundSplatsCheckBox_ = nullptr;
    QCheckBox* axesCheckBox_ = nullptr;
    QCheckBox* boundingBoxCheckBox_ = nullptr;
    QCheckBox* backstageShowLogCheckBox_ = nullptr;
    QCheckBox* routeWaypointShowCoordinatesCheckBox_ = nullptr;
    QCheckBox* routeWaypointShowCaptureAnglesCheckBox_ = nullptr;
    QCheckBox* routePartShowCoordinatesCheckBox_ = nullptr;
    QCheckBox* routePartShowCaptureAnglesCheckBox_ = nullptr;
    QCheckBox* invertOrbitCheckBox_ = nullptr;
    QCheckBox* invertPanCheckBox_ = nullptr;
    QCheckBox* invertWheelCheckBox_ = nullptr;
    QCheckBox* preferVegetationClassificationCheckBox_ = nullptr;
    QLabel* navigationTipsLabel_ = nullptr;
    QLineEdit* projectSearchEdit_ = nullptr;
    QLineEdit* backstageProjectPathLineEdit_ = nullptr;
    QListWidget* profileClassificationSourceListWidget_ = nullptr;
    QListWidget* profileClassificationTargetListWidget_ = nullptr;
    QListWidget* backstageRecentProjectsListWidget_ = nullptr;
    QTreeWidget* projectTreeWidget_ = nullptr;
    QTableWidget* towerTableWidget_ = nullptr;
    QTableWidget* issueTableWidget_ = nullptr;
    QTableWidget* classificationColorsTableWidget_ = nullptr;
    QTableWidget* clearanceSegmentsTableWidget_ = nullptr;
    QTableWidget* vegetationRisksTableWidget_ = nullptr;
    QTableWidget* routePartPointsTableWidget_ = nullptr;
    QTableWidget* routeWaypointsTableWidget_ = nullptr;
    QTableWidget* routeWaypointTargetsTableWidget_ = nullptr;
    QTableWidget* routeQaIssuesTableWidget_ = nullptr;
    QToolBar* measurementToolBar_ = nullptr;
    QToolBar* projectToolBar_ = nullptr;
    QToolBar* viewQuickToolBar_ = nullptr;
    QToolBar* towerToolBar_ = nullptr;
    QToolBar* issueToolBar_ = nullptr;
    QToolBar* analysisToolBar_ = nullptr;
    ProfilePlotWidget* profilePlotWidget_ = nullptr;
    QToolButton* issueMenuButton_ = nullptr;
    QMenu* issueActionsMenu_ = nullptr;
    QComboBox* logLevelFilterComboBox_ = nullptr;
    QLineEdit* logSearchLineEdit_ = nullptr;
    QCheckBox* logAutoScrollCheckBox_ = nullptr;
    QPushButton* logClearButton_ = nullptr;
    QPushButton* logExportButton_ = nullptr;
    QLabel* logStatsLabel_ = nullptr;
    QTextEdit* logTextEdit_ = nullptr;
    QLineEdit* towerCodeEdit_ = nullptr;
    QLineEdit* towerLineNameEdit_ = nullptr;
    QLineEdit* towerVoltageLevelEdit_ = nullptr;
    QComboBox* towerTypeComboBox_ = nullptr;
    QLineEdit* towerStructureTypeEdit_ = nullptr;
    QLineEdit* towerInspectionDateEdit_ = nullptr;
    QLineEdit* towerStatusEdit_ = nullptr;
    QPlainTextEdit* towerNotesEdit_ = nullptr;
    QLineEdit* issueTitleEdit_ = nullptr;
    QComboBox* issueCategoryComboBox_ = nullptr;
    QComboBox* issueSeverityComboBox_ = nullptr;
    QComboBox* issueStatusComboBox_ = nullptr;
    QComboBox* issueRelatedTowerComboBox_ = nullptr;
    QLineEdit* issueImagePathEdit_ = nullptr;
    QPlainTextEdit* issueDescriptionEdit_ = nullptr;
    QPushButton* resetClassificationColorsButton_ = nullptr;
    QPushButton* backstageProjectBrowseButton_ = nullptr;
    QPushButton* backstageProjectOpenButton_ = nullptr;
    QPushButton* backstageEditProjectPropertiesButton_ = nullptr;
    QPushButton* profileClassificationToggleButton_ = nullptr;
    QPushButton* profileClassificationSelectAllButton_ = nullptr;
    QPushButton* profileClassificationClearSelectionButton_ = nullptr;
    QPushButton* profileClassificationUndoButton_ = nullptr;
    QPushButton* profileClassificationRedoButton_ = nullptr;
    QPushButton* profileClassificationClearEditsButton_ = nullptr;
    QPushButton* profileClassificationSaveButton_ = nullptr;
    QLabel* profileClassificationModeLabel_ = nullptr;
    QLabel* profileClassificationStatusLabel_ = nullptr;
    QWidget* windowControlsWidget_ = nullptr;
    QToolButton* minimizeButton_ = nullptr;
    QToolButton* maximizeButton_ = nullptr;
    QToolButton* closeButton_ = nullptr;
    QProgressBar* globalProgressBar_ = nullptr;

    QAction* openAction_ = nullptr;
    QAction* addPointCloudAction_ = nullptr;
    QAction* removeDatasetAction_ = nullptr;
    QAction* locateDatasetAction_ = nullptr;
    QAction* copyDatasetPathAction_ = nullptr;
    QAction* expandProjectTreeAction_ = nullptr;
    QAction* collapseProjectTreeAction_ = nullptr;
    QAction* openProjectAction_ = nullptr;
    QAction* saveProjectAction_ = nullptr;
    QAction* saveProjectAsAction_ = nullptr;
    QAction* projectCoordinateSystemsAction_ = nullptr;
    QAction* clearAction_ = nullptr;
    QAction* exitAction_ = nullptr;
    QAction* fitSceneAction_ = nullptr;
    QAction* topViewAction_ = nullptr;
    QAction* frontViewAction_ = nullptr;
    QAction* rightViewAction_ = nullptr;
    QAction* showAxesAction_ = nullptr;
    QAction* showBoundingBoxAction_ = nullptr;
    QAction* darkBackgroundAction_ = nullptr;
    QAction* lightBackgroundAction_ = nullptr;
    QAction* rgbColorAction_ = nullptr;
    QAction* elevationColorAction_ = nullptr;
    QAction* singleColorAction_ = nullptr;
    QAction* classificationColorAction_ = nullptr;
    QAction* themeColorfulAction_ = nullptr;
    QAction* themeWhiteAction_ = nullptr;
    QAction* themeDarkGrayAction_ = nullptr;
    QAction* measureAction_ = nullptr;
    QAction* profileClassificationAction_ = nullptr;
    QAction* showProfileClassificationDockAction_ = nullptr;
    QAction* saveProfileClassificationEditsAction_ = nullptr;
    QAction* undoProfileClassificationAction_ = nullptr;
    QAction* redoProfileClassificationAction_ = nullptr;
    QAction* clearProfileClassificationEditsAction_ = nullptr;
    QAction* clearMeasurementAction_ = nullptr;
    QAction* exportClearanceCsvAction_ = nullptr;
    QAction* showProfileDockAction_ = nullptr;
    QAction* analyzeVegetationRisksAction_ = nullptr;
    QAction* focusVegetationRiskAction_ = nullptr;
    QAction* createIssueFromRiskAction_ = nullptr;
    QAction* createIssuesFromRisksAction_ = nullptr;
    QAction* clearVegetationRisksAction_ = nullptr;
    QAction* generateInspectionRouteAction_ = nullptr;
    QAction* regenerateInspectionRouteAction_ = nullptr;
    QAction* clearInspectionRouteAction_ = nullptr;
    QAction* toggleRouteEditingAction_ = nullptr;
    QAction* startInspectionRouteRoamAction_ = nullptr;
    QAction* pauseInspectionRouteRoamAction_ = nullptr;
    QAction* stopInspectionRouteRoamAction_ = nullptr;
    QAction* focusRouteWaypointAction_ = nullptr;
    QAction* importRouteFileAction_ = nullptr;
    QAction* saveRouteFileAction_ = nullptr;
    QAction* saveRouteFileAsAction_ = nullptr;
    QAction* reloadRouteFileAction_ = nullptr;
    QAction* importRouteKmlAction_ = nullptr;
    QAction* exportRouteKmlAction_ = nullptr;
    QAction* exportRouteDjiKmzAction_ = nullptr;
    QAction* startTowerEditAction_ = nullptr;
    QAction* finishTowerEditAction_ = nullptr;
    QAction* addTowerAction_ = nullptr;
    QAction* insertTowerAction_ = nullptr;
    QAction* moveTowerAction_ = nullptr;
    QAction* editCurrentTowerAction_ = nullptr;
    QAction* focusTowerAction_ = nullptr;
    QAction* removeTowerAction_ = nullptr;
    QAction* clearTowersAction_ = nullptr;
    QAction* cancelTowerToolAction_ = nullptr;
    QAction* importTowerFileAction_ = nullptr;
    QAction* saveTowerFileAction_ = nullptr;
    QAction* saveTowerFileAsAction_ = nullptr;
    QAction* reloadTowerFileAction_ = nullptr;
    QAction* showTowerXAction_ = nullptr;
    QAction* showTowerYAction_ = nullptr;
    QAction* showTowerZAction_ = nullptr;
    QAction* startIssueMarkAction_ = nullptr;
    QAction* cancelIssueToolAction_ = nullptr;
    QAction* focusIssueAction_ = nullptr;
    QAction* removeIssueAction_ = nullptr;
    QAction* clearIssuesAction_ = nullptr;
    QAction* exportIssuesCsvAction_ = nullptr;
    QAction* exportInspectionReportAction_ = nullptr;
    QAction* showLogAction_ = nullptr;
    QAction* languageEnglishAction_ = nullptr;
    QAction* languageChineseAction_ = nullptr;

    QActionGroup* colorModeActionGroup_ = nullptr;
    QActionGroup* themeActionGroup_ = nullptr;
    QActionGroup* languageActionGroup_ = nullptr;
    QString currentProjectFilePath_;
    QString linkedTowerFilePath_;
    QString linkedRouteFilePath_;
    bool updatingProjectTree_ = false;
    bool towerEditingEnabled_ = false;
    double clearanceWarningThresholdMeters_ = 10.0;
    ClearanceRulePreset clearanceRulePreset_ = ClearanceRulePreset::TransmissionCorridor;
    double vegetationSearchRadiusMeters_ = 20.0;
    double vegetationClusterGapMeters_ = 8.0;
    int vegetationClusterPointCount_ = 3;
    bool preferVegetationClassification_ = true;
    QList<VegetationRiskRecord> vegetationRiskResults_;
    int selectedVegetationRiskIndex_ = -1;
    lasviewer::crs::ProjectCoordinateSystems projectCoordinateSystems_ {
        lasviewer::crs::CoordinateSystemRef(),
        lasviewer::crs::defaultGeographicCoordinateSystem()
    };
    RoutePlanningOptions routePlanningOptions_;
    PowerlineRouteDocument currentPowerlineRoute_;
    RouteQaReport routeQaReport_;
    int selectedRoutePartIndex_ = -1;
    int selectedRouteWaypointIndex_ = -1;
    int selectedRouteWaypointTargetIndex_ = -1;
    int selectedRouteQaIssueIndex_ = -1;
    bool routeEditingEnabled_ = false;
    bool updatingRouteTables_ = false;
    bool updatingTowerDetails_ = false;
    bool updatingIssueDetails_ = false;
    bool updatingClassificationColorTable_ = false;
    QString routeRoamLastCaptureSummary_;
    bool classificationEditsDirty_ = false;
    bool handlingProfileClassificationExitPrompt_ = false;
    bool savingProfileClassificationEdits_ = false;
    QMap<int, QString> classificationNameOverrides_;
};
