include_guard(GLOBAL)

set(LAS_VIEWER_APP_ENTRY_SOURCES
    src/main.cpp
)

set(LAS_VIEWER_SMOKE_ENTRY_SOURCES
    examples/viewer_smoke_test.cpp
)

set(LAS_VIEWER_COMMON_SOURCES
    resources.qrc
    src/crs/CrsCatalogService.cpp
    src/crs/CrsAuthorityService.cpp
    src/crs/CrsProjRuntime.cpp
    src/crs/CrsSelectionDialog.cpp
    src/crs/CrsTransformService.cpp
    src/crs/CrsTypes.cpp
    src/crs/ProjectCoordinateSystemsDialog.cpp
    src/crs/RecentCrsStore.cpp
    src/domain/AnalysisData.cpp
    src/domain/ClassificationEditStore.cpp
    src/domain/ClearanceAnalysis.cpp
    src/domain/ClearanceReportExporter.cpp
    src/domain/DataManager.cpp
    src/domain/InspectionData.cpp
    src/domain/InspectionReportExporter.cpp
    src/domain/ProfileMarkerProjection.cpp
    src/domain/RuleBasedClearanceEngine.cpp
    src/domain/TowerFileInterop.cpp
    src/domain/VegetationRiskAnalysis.cpp
    src/gui/ApplicationLogDock.cpp
    src/gui/BackstageAboutWidget.cpp
    src/gui/BackstageAboutWidget.ui
    src/gui/BackstageApplicationSettingsWidget.cpp
    src/gui/BackstageApplicationSettingsWidget.ui
    src/gui/BackstageOpenActionsWidget.cpp
    src/gui/BackstageOpenActionsWidget.ui
    src/gui/BackstageOpenProjectWidget.cpp
    src/gui/BackstageOpenProjectWidget.ui
    src/gui/BackstagePageHeaderWidget.cpp
    src/gui/BackstagePageHeaderWidget.ui
    src/gui/BackstageProjectPropertiesWidget.cpp
    src/gui/BackstageProjectPropertiesWidget.ui
    src/gui/DatasetSummaryWidget.cpp
    src/gui/DatasetSummaryWidget.ui
    src/gui/IssueController.cpp
    src/gui/IssueEditorWidget.cpp
    src/gui/IssueEditorWidget.ui
    src/gui/MainWindow.cpp
    src/gui/MainWindow.Actions.cpp
    src/gui/MainWindow.Backstage.cpp
    src/gui/MainWindow.Connections.cpp
    src/gui/MainWindow.Helpers.cpp
    src/gui/MainWindow.Core.cpp
    src/gui/MainWindow.Docks.cpp
    src/gui/MainWindow.PointCloud.cpp
    src/gui/MainWindow.ProjectSerializer.cpp
    src/gui/MainWindow.SettingsStore.cpp
    src/gui/MainWindow.Route.cpp
    src/gui/MainWindow.Ribbon.cpp
    src/gui/MainWindow.TowerIssue.cpp
    src/gui/MeasurementAnalysisController.cpp
    src/gui/NavigationSettingsWidget.cpp
    src/gui/NavigationSettingsWidget.ui
    src/gui/PointCloudViewer.cpp
    src/gui/ProfileClassificationController.cpp
    src/gui/ProfileClassificationDock.cpp
    src/gui/ProfileClassificationWidget.cpp
    src/gui/ProfileClassificationWidget.ui
    src/gui/ProjectExplorerController.cpp
    src/gui/ProjectExplorerDock.cpp
    src/gui/RouteController.cpp
    src/gui/RouteDetailsDock.cpp
    src/gui/SceneInspectorDock.cpp
    src/gui/SpanProfileDock.cpp
    src/gui/TowerController.cpp
    src/gui/TowerEditorWidget.cpp
    src/gui/TowerEditorWidget.ui
    src/gui/UiHistoryStore.cpp
    src/gui/VisualizationPanelController.cpp
    src/gui/support/RibbonIconFactory.cpp
    src/gui/support/UiHelpers.cpp
    src/gui/ProfilePlotWidget.cpp
    src/logging/ApplicationLogger.cpp
    src/pointcloud/LasReader.cpp
    src/pointcloud/PointCloudData.cpp
    src/pointcloud/PointCloudTileStore.cpp
    src/osg/OsgPointCloudNode.cpp
    src/route/InspectionRoutePlanning.cpp
    src/route/PowerlineRouteBridge.cpp
    src/route/PowerlineRouteJson.cpp
    src/route/RouteInterop.cpp
)

if(WIN32)
    list(APPEND LAS_VIEWER_COMMON_SOURCES src/app_icon.rc)
endif()

set(LAS_VIEWER_COMMON_HEADERS
    src/crs/CrsCatalogService.h
    src/crs/CrsAuthorityService.h
    src/crs/CrsProjRuntime.h
    src/crs/CrsSelectionDialog.h
    src/crs/CrsTransformService.h
    src/crs/CrsTypes.h
    src/crs/LASViewerCrsExport.h
    src/crs/ProjectCoordinateSystemsDialog.h
    src/crs/RecentCrsStore.h
    src/domain/AnalysisData.h
    src/domain/ClassificationEditStore.h
    src/domain/ClearanceAnalysis.h
    src/domain/ClearanceReportExporter.h
    src/domain/DataManager.h
    src/domain/InspectionData.h
    src/domain/InspectionReportExporter.h
    src/domain/ProjectMetadata.h
    src/domain/ProfileMarkerProjection.h
    src/domain/RuleBasedClearanceEngine.h
    src/domain/TowerFileInterop.h
    src/domain/VegetationRiskAnalysis.h
    src/gui/ApplicationLogDock.h
    src/gui/BackstageAboutWidget.h
    src/gui/BackstageApplicationSettingsWidget.h
    src/gui/BackstageOpenActionsWidget.h
    src/gui/BackstageOpenProjectWidget.h
    src/gui/BackstagePageHeaderWidget.h
    src/gui/BackstageProjectPropertiesWidget.h
    src/gui/DatasetSummaryWidget.h
    src/gui/IssueController.h
    src/gui/IssueEditorWidget.h
    src/gui/MainWindow.h
    src/gui/MeasurementAnalysisController.h
    src/gui/NavigationSettingsWidget.h
    src/gui/PointCloudViewer.h
    src/gui/ProfileClassificationController.h
    src/gui/ProfileClassificationDock.h
    src/gui/ProfileClassificationWidget.h
    src/gui/ProjectExplorerController.h
    src/gui/ProjectExplorerDock.h
    src/gui/RouteController.h
    src/gui/RouteDetailsDock.h
    src/gui/SceneInspectorDock.h
    src/gui/SpanProfileDock.h
    src/gui/TowerController.h
    src/gui/TowerEditorWidget.h
    src/gui/VisualizationPanelController.h
    src/gui/ProfilePlotWidget.h
    src/gui/support/RibbonIconFactory.h
    src/gui/support/SettingsKeys.h
    src/gui/support/UiHelpers.h
    src/gui/UiHistoryStore.h
    src/logging/ApplicationLogger.h
    src/pointcloud/LasReader.h
    src/pointcloud/PointCloudData.h
    src/pointcloud/PointCloudTileStore.h
    src/osg/PointCloudVisualization.h
    src/osg/OsgPointCloudNode.h
    src/route/InspectionRoutePlanning.h
    src/route/PowerlineRouteBridge.h
    src/route/PowerlineRouteJson.h
    src/route/PowerlineRouteTypes.h
    src/route/RouteInterop.h
)
